name: Tecton Feature Repo CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    plan:
        runs-on: ubuntu-latest
        environment: env-dev
        outputs:
          planid: ${{ steps.planid.outputs.planid }}
        env:
            TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
            API_SERVICE: ${{ secrets.API_SERVICE }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: 3.9
                cache: pip
            - run: pip install -r requirements.txt

            - name: Select workspace
              run: tecton worksapce select ${TECTON_WORKSPACE}


            - name: Run Tecton plan
              run: tecton plan | tee output.log
            
            - name: Extract plan output
              id: planid
              run: |
                PLANID=$(cat output.log | perl -wne  '/Generated plan ID is ([0-9a-f]+)/i and print $1')         
                echo "planid=$PLANID" >> "$GITHUB_OUTPUT"
